### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by mstraa** [gdias/Angular-Modules-Bootsrap#1]
Hi !
First thanks for your hard work !
When I launch the server I've got an blank page. I tried some URL /about, /home, changed the port to 9090 ... But nothing.

I made a certificate but it's still red up there. Can this be the problem ?
Any idea why this behaviour ? 

`[00:25:49] Using gulpfile ~\CryptoCheck\CryptoCheck\gulpfile.js
[00:25:49] Starting 'start'...
[00:25:49] Finished 'start' after 99 ms
[00:25:49] Starting 'watch'...
[00:25:49] Finished 'watch' after 77 ms
[00:25:49] Starting 'browserify'...
[00:25:49] Starting 'sass'...
[00:25:49] [nodemon] 1.11.0
[00:25:49] [nodemon] to restart at any time, enter `rs`
[00:25:49] [nodemon] watching: server/**/*
[00:25:49] [nodemon] starting `node server/server.js`
[00:25:49] Finished 'sass' after 75 ms
The APP is hosted on : 9090 port
[00:25:53] Finished 'browserify' after 3.63 s
[00:25:53] Starting 'default'...
[00:25:53] Finished 'default' after 2.79 µs
GET / 200 6.499 ms - 502
GET /css/styles.css 200 7.652 ms - 429
GET /css/bootstrap.min.css 200 7.876 ms - 95563
GET /js/main.js 200 17.679 ms - 2253778`

**Comment by gdias** [comment]
Hello mstraa,
Thanks for your feedback. 
First, you have need to a MongoDB Server started on 27017 port to display this bootstrap.
Others thing who can to explain this blank page, is the node version. What is your version of Node ?
I'm so sorry, i restart the dev of this package, and many versions of NodeJS are out since last commit. I hope to have help you.

**Comment by mstraa** [comment]
Hey,
MongoDB was started. I had install nodeJS 6 because the latest was launching npm install with errors.
I know the vendors update are the worst ....
I will retry in a month or two I think, I just bought a house ! ^^

**Comment by gdias** [comment]
Hi mstraa, 
I have a good news for you, i just update angular version and theses different plugin in 1.6.4 (latest version of angular 1.x), and it's works ! 
Many thanks for your contact, you've really help me to maintain it.

PS : My tests are done under nodeJS v.6.2.2 ;)

**Comment by gdias** [comment]
I just updated the package.json and gulpfile.js with right versions of package, remove old and update code with the new package
Ready now for version 7 of NodeJS.
Enjoy !
